jobs:
  enforcer:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: date
      name: Get current week within the year
      run: echo "::set-output name=week_of_year::$(date +'%W' --utc)"
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      name: Install Maven modules to local Maven repository
      run: 'mvn install -B -ntp  -T 1C -DskipTests -Dclirr.skip -Dcheckstyle.skip

        '
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      run: mvn -B -ntp enforcer:enforce@enforce -T 1C
  gapic-libraries-bom:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Install Maven modules to local Maven repository
      run: 'mvn install -B -ntp  -T 1C -DskipTests -Dclirr.skip -Dcheckstyle.skip

        '
    - continue-on-error: true
      name: Validate gapic-libraries-bom
      uses: googleapis/java-cloud-bom/tests/validate-bom@v26.13.0
      with:
        bom-path: gapic-libraries-bom/pom.xml
  lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: date
      name: Get current week within the year
      run: echo "::set-output name=week_of_year::$(date +'%W' --utc)"
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      id: mvn-cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-unified-${{ steps.date.outputs.week_of_year }}
        path: ~/.m2/repository
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      run: mvn -B -ntp com.coveo:fmt-maven-plugin:check
    - continue-on-error: true
      run: mvn -B -ntp checkstyle:check@checkstyle
  units:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: date
      name: Get current week within the year
      run: echo "::set-output name=week_of_year::$(date +'%W' --utc)"
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{matrix.java}}
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      id: mvn-cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-unified-${{ steps.date.outputs.week_of_year }}
        path: ~/.m2/repository
    - continue-on-error: true
      env:
        JOB_NAME: units-${{matrix.java}}
        JOB_TYPE: test
      run: .kokoro/build.sh
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
  windows:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Support longpaths
      run: git config --system core.longpaths true
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      env:
        JOB_NAME: windows-units
        JOB_TYPE: test
      run: .kokoro/build.sh
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
