jobs:
  update:
    if: github.repository_owner == 'googleapis'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Replace sha256 value in OwlBot to the latest value
      run: "# https://cloud.google.com/kubernetes-engine/docs/archive/using-container-images#container_registry\n\
        sha256=$(curl -s -I -H \"Accept: application/vnd.docker.distribution.manifest.v2+json\"\
        \ \\\n    \"https://gcr.io/v2/cloud-devrel-public-resources/owlbot-java/manifests/latest\"\
        \ \\\n    |grep -i docker-content-digest | awk '{print $2}' | tr -d '\\r')\n\
        echo \"The latest sha256 is ${sha256}\"\nsed -i.bak -e \"s/digest: sha256.*/digest:\
        \ ${sha256}/\" .github/.OwlBot.lock.yaml\nrm .github/.OwlBot.lock.yaml.bak\n"
      shell: bash
    - continue-on-error: true
      env:
        ACCESS_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
      uses: googleapis/code-suggester@v4
      with:
        branch: update-owlbot-lock
        command: pr
        description: Updating OwlBot.lock sha256 value to the latest
        force: true
        git_dir: .
        message: 'chore: updating OwlBot.lock sha256 value to the latest'
        primary: main
        title: 'chore: updating OwlBot.lock sha256 value to the latest'
        upstream_owner: googleapis
        upstream_repo: google-cloud-java
name: owlbot_lock_update
on:
  repository_dispatch:
    types: trigger-ga___owlbot_sha256.yaml
