jobs:
  update:
    if: github.repository_owner == 'googleapis'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-python@v4
      with:
        architecture: x64
        python-version: '3.7'
    - continue-on-error: true
      run: python3 -m pip install --require-hashes -r .github/requirements.txt
    - continue-on-error: true
      run: python3 generate-readme.py
    - continue-on-error: true
      env:
        ACCESS_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
      uses: googleapis/code-suggester@v4
      with:
        branch: update-readme
        command: pr
        description: ran python3 generate-readme.py
        force: true
        git_dir: .
        message: 'chore: regenerate client table in README'
        primary: main
        title: 'chore: regenerate client table in README'
        upstream_owner: googleapis
        upstream_repo: google-cloud-java
name: readme
on:
  repository_dispatch:
    types: trigger-ga___readme.yaml
