jobs:
  update-googleapis-commit:
    env:
      base_branch: main
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.CLOUD_JAVA_BOT_TOKEN }}
      name: Update googleapis commit to latest
      run: "set -x\n[ -z \"$(git config user.email)\" ] && git config --global user.email\
        \ \"cloud-java-bot@google.com\"\n[ -z \"$(git config user.name)\" ] && git\
        \ config --global user.name \"cloud-java-bot\"\nbash generation/update_googleapis_commit.sh\
        \ \\\n  --base_branch \"${base_branch}\"\\\n  --repo ${{ github.repository\
        \ }}\n"
      shell: bash
name: Update googleapis commit
on:
  repository_dispatch:
    types: trigger-ga___update_googleapis_commit.yaml
