jobs:
  generate:
    env:
      API_PRETTY_NAME: API Keys
      API_SHORT_NAME: apikeys
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-python@v4
      with:
        cache: pip
        python-version: '3.9'
    - continue-on-error: true
      id: date
      name: Get current week within the year
      run: echo "::set-output name=week_of_year::$(date +'%W' --utc)"
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      id: mvn-cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-unified-${{ steps.date.outputs.week_of_year }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Install new-client.py dependencies
      run: pip install --require-hashes -r generation/new_client/requirements.txt
    - continue-on-error: true
      name: Remove Client
      run: 'rm -rf java-${API_SHORT_NAME} || true

        sed -i "/${API_SHORT_NAME}/d" pom.xml

        sed -i "/${API_SHORT_NAME}/d" gapic-libraries-bom/pom.xml

        '
    - continue-on-error: true
      name: Verify Client Removal
      run: '! test -d java-${API_SHORT_NAME}

        ! grep -q ${API_SHORT_NAME} pom.xml

        ! grep -q ${API_SHORT_NAME} gapic-libraries-bom/pom.xml

        '
    - continue-on-error: true
      name: Generate
      run: "python generation/new_client/new-client.py generate \\\n    --api_shortname=${API_SHORT_NAME}\
        \ \\\n    --proto-path=google/api/${API_SHORT_NAME} \\\n    --name-pretty=\"\
        ${API_PRETTY_NAME}\" \\\n    --product-docs=\"https://github.com/googleapis/google-cloud-java/tree/main/java-${API_SHORT_NAME}\"\
        \ \\\n    --api-description=\"${API_PRETTY_NAME} Client lets you use ${API_PRETTY_NAME}\
        \ API.\" \\\n    --googleapis-gen-url=https://cloud-java-bot:${{ secrets.CLOUD_JAVA_BOT_TOKEN\
        \ }}@github.com/googleapis/googleapis-gen.git\n"
    - continue-on-error: true
      name: Push to branch (helpful for troubleshooting)
      run: '[ -z "`git config user.email`" ] && git config --global user.email "${USERNAME:-script}@google.com"

        [ -z "`git config user.name`" ] && git config --global user.name "${USERNAME:-script}"

        git checkout -b newclient_output_${{ github.event_name }}

        git add --all

        git commit -m ''feat: re-generated ${API_SHORT_NAME}''

        git remote add monorepo https://${{ github.actor }}:${{ github.token }}@github.com/${{
        github.repository }}.git

        git fetch -q --unshallow monorepo

        git push -f monorepo newclient_output_${{ github.event_name }}

        '
    - continue-on-error: true
      name: Verify Client Creation
      run: 'test -d java-${API_SHORT_NAME}

        grep -q ${API_SHORT_NAME} pom.xml

        grep -q ${API_SHORT_NAME} gapic-libraries-bom/pom.xml

        '
    - continue-on-error: true
      name: Test
      run: mvn -B -ntp test -T 1C
name: Verify GAPIC client library generation
on:
  repository_dispatch:
    types: trigger-ga___verify-client-generation.yaml
